#!/usr/bin/env python3
"""Writes tests/windower_events_test.txt: an --addon-harness script that feeds synthetic server
packets (layouts as the game uses them) to tests/addons/wevtest and asks windower_events.lua for
its state. tests/windower_events_test.sh runs it and compares with windower_events_test.expected."""
import os
import struct

OUT = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'windower_events_test.txt')
ME = 0x01020304
ME_INDEX = 0x400


def packet(pid, size, fields):
    b = bytearray(size)
    struct.pack_into('<HH', b, 0, pid, 0x10)
    for off, fmt, val in fields:
        if fmt == 's':
            b[off:off + len(val)] = val
        else:
            struct.pack_into('<' + fmt, b, off, val)
    return b


class Bits:
    """Least-significant-first bit writer (the 0x028 layout)."""

    def __init__(self, nbytes):
        self.b = bytearray(nbytes)

    def put(self, pos, n, v):
        for i in range(n):
            if (v >> i) & 1:
                p = pos + i
                self.b[p // 8] |= 1 << (p % 8)
        return pos + n


def action():
    w = Bits(0x80)
    struct.pack_into('<HH', w.b, 0, 0x028, 0x10)
    w.b[4] = 0x40  # size byte
    w.put(40, 32, ME)          # actor
    w.put(72, 10, 2)           # target count
    w.put(82, 4, 1)            # category: melee
    w.put(86, 16, 0)           # param
    w.put(102, 16, 0x6B30)     # unknown
    w.put(118, 32, 0)          # recast
    pos = 150
    # target 1: two actions, the second with an added effect
    pos = w.put(pos, 32, 0x0100200A)
    pos = w.put(pos, 4, 2)
    for i, add in ((0, False), (1, True)):
        w.put(pos, 5, 8)            # reaction
        w.put(pos + 5, 12, 1)       # animation
        w.put(pos + 17, 4, 2)       # effect
        w.put(pos + 21, 3, 1)       # stagger
        w.put(pos + 24, 3, 0)       # knockback
        w.put(pos + 27, 17, 123 + i)  # param (damage)
        w.put(pos + 44, 10, 1)      # message
        w.put(pos + 54, 31, 0)
        pos = w.put(pos + 85, 1, 1 if add else 0)
        if add:
            w.put(pos, 6, 1)
            w.put(pos + 6, 4, 3)
            w.put(pos + 10, 17, 45)
            w.put(pos + 27, 10, 163)
            pos += 37
        pos = w.put(pos, 1, 0)  # no spikes
    # target 2: one action with spikes
    pos = w.put(pos, 32, 0x0100200B)
    pos = w.put(pos, 4, 1)
    w.put(pos, 5, 1)
    w.put(pos + 27, 17, 7)
    w.put(pos + 44, 10, 15)  # miss
    pos = w.put(pos + 85, 1, 0)
    pos = w.put(pos, 1, 1)
    w.put(pos, 6, 2)
    w.put(pos + 6, 4, 1)
    w.put(pos + 10, 14, 30)
    w.put(pos + 24, 10, 33)
    pos += 34
    n = (pos + 7) // 8
    return w.b[:(n + 3) & ~3]


def zone_in(zone, weather):
    return packet(0x00A, 0x104, [
        (0x04, 'I', ME), (0x08, 'H', ME_INDEX), (0x1E, 'B', 100), (0x1F, 'B', 0),
        (0x30, 'H', zone), (0x68, 'H', weather), (0x84, 's', b'Josh'),
        (0xB4, 'B', 5), (0xB7, 'B', 3), (0xBC + 5, 'B', 75), (0xBC + 3, 'B', 37),
        (0xE8, 'I', 1000), (0xEC, 'I', 500)])


def item_assign(bag, slot, item, count, status=0):
    return packet(0x01F, 0x10, [(0x04, 'I', count), (0x08, 'H', item), (0x0A, 'B', bag), (0x0B, 'B', slot),
                                (0x0C, 'B', status)])


def item_update(bag, slot, item, count, status=0, ext=b''):
    return packet(0x020, 0x2C, [(0x04, 'I', count), (0x08, 'I', 0), (0x0C, 'H', item), (0x0E, 'B', bag),
                                (0x0F, 'B', slot), (0x10, 'B', status), (0x11, 's', ext)])


def ls_extdata(name):
    """A linkshell's extdata: id, colour, status 1, then the name in 6-bit characters, msb first."""
    b = bytearray(24)
    struct.pack_into('<I', b, 0, 77)
    b[6], b[7], b[8] = 0x3F, 0x0F, 1
    bits = []
    for c in name:
        v = ord(c) - 96 if c.islower() else ord(c) - 64 + 26
        bits += [(v >> (5 - k)) & 1 for k in range(6)]
    for i, x in enumerate(bits):
        if x:
            p = 72 + i
            b[p // 8] |= 0x80 >> (p % 8)
    return bytes(b)


def char_update(buffs, status):
    fields = [(0x24, 'I', ME), (0x30, 'B', status), (0x5C, 'B', 0x03)]
    ids = buffs + [255] * (32 - len(buffs))
    mask = bytearray(8)
    for i, v in enumerate(ids):
        fields.append((0x04 + i, 'B', v & 0xFF))
        mask[i // 4] |= (v >> 8) << (2 * (i % 4))
    fields.append((0x4C, 's', bytes(mask)))
    return packet(0x037, 0x60, fields)


def vitals(hp, mp, tp, hpp, mpp):
    return packet(0x0DF, 0x28, [(0x04, 'I', ME), (0x08, 'I', hp), (0x0C, 'I', mp), (0x10, 'I', tp),
                                (0x14, 'H', ME_INDEX), (0x16, 'B', hpp), (0x17, 'B', mpp),
                                (0x20, 'B', 5), (0x21, 'B', 75), (0x22, 'B', 3), (0x23, 'B', 37)])


def hexs(b):
    return ' '.join('%02x' % x for x in b)


lines = []


def L(s):
    lines.append(s)


def pin(b, note):
    L('# ' + note)
    L('packet_in ' + hexs(b))


L('# Generated by tests/gen_windower_events_test.py; run by tests/windower_events_test.sh')
L('load wevtest xi')
L('echo --- login, bags, items')
pin(zone_in(230, 1), '0x00A zone in: login')
bags = bytearray(0x44)
struct.pack_into('<HH', bags, 0, 0x01C, 0x10)
for b, n in ((0, 81), (1, 81), (5, 81), (8, 81), (11, 81)):
    bags[4 + b] = n
    struct.pack_into('<H', bags, 0x24 + 2 * b, n)
pin(bags, '0x01C bag sizes')
pin(item_assign(0, 0, 0xFFFF, 123456), '0x01F gil (before 0x01D: no add item)')
pin(item_assign(0, 1, 4096, 12), '0x01F inventory 1: 12 fire crystals')
pin(item_update(0, 2, 16555, 1, 5, bytes(range(1, 25))), '0x020 inventory 2: an equipped item with extdata')
pin(packet(0x050, 0x08, [(0x04, 'B', 2), (0x05, 'B', 0), (0x06, 'B', 0)]), '0x050 equip slot 0 <- inventory 2')
pin(packet(0x01D, 0x0C, [(0x04, 'B', 1), (0x05, 'B', 18)]), '0x01D all bags loaded')
pin(item_assign(0, 5, 4097, 3), '0x01F inventory 5: add item')
pin(packet(0x01E, 0x0C, [(0x04, 'I', 0), (0x08, 'B', 0), (0x09, 'B', 5)]), '0x01E inventory 5 gone: remove item')
pin(item_update(0, 6, 513, 1, 0x13, ls_extdata('Josh')), '0x020 an equipped linkshell: add item, linkshell change')
L('lua wevtest ser(wev.get_items(0, 1))')
L('lua wevtest ser(wev.get_items(0, 2))')
L('lua wevtest ser(wev.get_items("gil"))')
L('lua wevtest ser(wev.get_items("equipment").main) .. " " .. ser(wev.get_items("equipment").main_bag)')
L('lua wevtest ser({max = wev.get_items("inventory").max, count = wev.get_items().inventory.count, en = wev.get_items().wardrobe3.enabled})')

L('echo --- buffs, status, vitals, jobs')
pin(char_update([1, 33, 33, 300], 0), '0x037 first: no events')
pin(char_update([33, 300, 40, 257], 1), '0x037: lose 1 and a 33, gain 40 and 257, status 0 -> 1')
pin(vitals(900, 400, 1000, 90, 80), '0x0DF first: no events')
pin(vitals(850, 400, 1500, 85, 80), '0x0DF: hp, tp, hpp change')
pin(packet(0x061, 0x70, [(0x04, 'I', 1100), (0x08, 'I', 300), (0x0C, 'B', 16), (0x0D, 'B', 75),
                         (0x0E, 'B', 3), (0x0F, 'B', 37), (0x50, 'B', 2), (0x54, 'B', 119)]),
    '0x061: main job BLU: job change')
blu = packet(0x044, 0x9C, [(0x04, 'B', 16), (0x05, 'B', 0)] + [(0x08 + i, 'B', v) for i, v in enumerate((1, 2, 0, 5))])
pin(blu, '0x044 BLU set spells')
L('lua wevtest ser(wev.get_mjob_data().spells)')
pup = packet(0x044, 0x9C, [(0x04, 'B', 18), (0x05, 'B', 1), (0x08, 'B', 1), (0x09, 'B', 0x20), (0x0A, 'B', 0xA2),
                           (0x18, 'I', 0b110), (0x38, 'I', 0b1), (0x58, 's', b'Luvbot'), (0x68, 'H', 500)])
pin(pup, '0x044 PUP as sub job')
L('lua wevtest ser(wev.get_sjob_data().attachments) .. ser(wev.get_sjob_data().name) .. ser(wev.get_sjob_data().available_heads)')
L('lua wevtest ser(wev.get_player_extra().buffs) .. " " .. ser(wev.get_player_extra().vitals)')

L('echo --- action, messages, chat')
pin(action(), '0x028 melee: two targets, an added effect and spikes')
pin(packet(0x029, 0x1C, [(0x04, 'I', ME), (0x08, 'I', 0x0100200A), (0x0C, 'I', 11), (0x10, 'I', 22),
                         (0x14, 'H', ME_INDEX), (0x16, 'H', 10), (0x18, 'H', 6)]), '0x029 action message')
L('lua wevtest replace_in[0x029] = function(m) return m:sub(1, 0x18) .. string.char(7, 0) .. m:sub(0x1B) end')
pin(packet(0x029, 0x1C, [(0x04, 'I', ME), (0x08, 'I', 5), (0x18, 'H', 6)]), '0x029 changed by the chunk handler: message 7')
L('lua wevtest replace_in[0x029] = nil')
pin(packet(0x02D, 0x1C, [(0x04, 'I', ME), (0x08, 'I', 9), (0x10, 'I', 250), (0x14, 'I', 3), (0x18, 'H', 253)]),
    '0x02D exp chain')
pin(packet(0x02D, 0x1C, [(0x04, 'I', ME), (0x10, 'I', 76), (0x18, 'H', 9)]), '0x02D level up')
pin(packet(0x017, 0x30, [(0x04, 'B', 3), (0x05, 'B', 0), (0x08, 's', b'Friend'), (0x17, 's', b'hello there')]),
    '0x017 a tell')
pin(packet(0x05A, 0x38, [(0x04, 'I', 0x0100200C), (0x08, 'I', ME), (0x10, 'H', 12), (0x16, 'B', 2)]), '0x05A emote')
pin(packet(0x009, 0x30, [(0x04, 'I', 0x0100200C), (0x08, 'H', 0x401), (0x0A, 'H', 89), (0x0D, 's', b'Friend')]),
    '0x009 examined')
pin(packet(0x0DC, 0x20, [(0x04, 'I', 0x0100200C), (0x0C, 's', b'Friend')]), '0x0DC party invite')
L('lua wevtest block_in[0x0DC] = true')
pin(packet(0x0DC, 0x20, [(0x04, 'I', 0x0100200C), (0x0C, 's', b'Friend')]), '0x0DC blocked: no party invite, 0 bytes out')
L('lua wevtest block_in[0x0DC] = nil')
L('packet_out 15 00 00 00 00 00 00 00')

L('echo --- known things, recasts, merits')
ki = packet(0x055, 0x88, [(0x04, 'B', 0b1010), (0x84, 'I', 1)])
pin(ki, '0x055 key items, table 1: ids 513 and 515')
pin(packet(0x0AA, 0x84, [(0x04, 'B', 0b110)]), '0x0AA spells 1 and 2')
L('lua wevtest ser(wev.get_key_items()) .. " " .. ser({wev.get_spells()[1], wev.get_spells()[2], wev.get_spells()[3]})')
ab = packet(0x0AC, 0xE4, [(0x04, 'B', 0b1), (0x44 + 2, 'B', 0b1), (0x84, 'B', 0b10), (0xC4, 'B', 0b100)])
pin(ab, '0x0AC abilities: ws 0, ja 16, pet 513, trait 2')
L('lua wevtest ser(wev.get_abilities())')
pin(packet(0x119, 0x100, [(0x04, 'H', 300), (0x07, 'B', 0), (0x0C, 'H', 60), (0x0F, 'B', 5)]), '0x119 recasts')
L('lua wevtest local r = wev.get_ability_recasts() return (r[0] > 290 and r[0] <= 300) and (r[5] > 50) and r[6] == 0')
pin(packet(0x08C, 0x14, [(0x04, 'B', 2), (0x08, 'H', 64), (0x0A, 'B', 3), (0x0B, 'B', 5),
                         (0x0C, 'H', 194), (0x0F, 'B', 2)]), '0x08C merits')
pin(packet(0x063, 0xD0, [(0x04, 'H', 5), (0x0C + 6 * 16, 'H', 1234), (0x0E + 6 * 16, 'H', 20)]), '0x063 job points')
pin(packet(0x063, 0x0D0, [(0x04, 'H', 9), (0x08, 'H', 33), (0x0A, 'H', 0xFF)]), '0x063 buff times')
pin(packet(0x062, 0x100, [(0x80 + 2 * 3, 'H', 250 | 0x8000), (0xE0 + 2 * 8, 'H', (60 << 5) | 7)]), '0x062 skills')
L('lua wevtest local p = wev.get_player_extra() return ser(p.merits) .. ser(p.job_points.blu.cp) .. ser(p.skills.sword) .. ser(p.skills.cooking) .. ser(p.item_level) .. ser(p.buff_details[1].id)')
pin(packet(0x0D2, 0x3C, [(0x08, 'I', 0x0100200A), (0x0C, 'I', 1), (0x10, 'H', 4096), (0x14, 'B', 3)]), '0x0D2 treasure')
L('lua wevtest ser(wev.get_items("treasure"))')

L('echo --- weather, zone, clock, logout')
pin(packet(0x057, 0x0C, [(0x04, 'I', 0), (0x08, 'B', 4)]), '0x057 weather 4')
pin(zone_in(231, 4), '0x00A to zone 231: zone change')
L('lua wevtest fake_now = 1790000000')
L('frames 1')
L('lua wevtest fake_now = 1790000003')
L('frames 1')
L('lua wevtest fake_now = 1790000003 + 3456')
L('frames 1')
L('lua wevtest ser(wev.get_info())')
L('lua wevtest ser(wev.parse_action(string.char(0x28, 0x10, 0, 0, 0x14, 4, 3, 2, 1)).actor_id)')
pin(packet(0x00B, 0x1C, [(0x04, 'I', 1)]), '0x00B type 1: logout')
L('lua wevtest ser(wev.get_info().logged_in)')

with open(OUT, 'w') as f:
    f.write('\n'.join(lines) + '\n')
print('wrote', OUT)
