"""Embed the addon host's Lua (host/addons/lua/*.lua) and fonts (assets/fonts/*.ttf, as
"font/<name>") into generated/addons_lua.c.

  python3 tools/embed_lua.py

host/addons/core.c runs them from memory (xi_embedded): xi.lua in every addon's state, then the
kind's layer (ashita.lua, windower.lua) and whatever those require from the host (a module under
host/addons/lua/ is reachable as require('xi.<name>')). Rewritten only when the text changes.
"""
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
SRC = os.path.join(ROOT, 'host', 'addons', 'lua')
FONTS = os.path.join(ROOT, 'assets', 'fonts')
OUT = os.path.join(ROOT, 'generated', 'addons_lua.c')


def main():
    files = [(f[:-4], os.path.join(SRC, f)) for f in sorted(os.listdir(SRC)) if f.endswith('.lua')]
    if os.path.isdir(FONTS):
        files += [('font/' + f[:-4], os.path.join(FONTS, f)) for f in sorted(os.listdir(FONTS)) if f.endswith('.ttf')]
    names = [n for n, _ in files]
    path_of = dict(files)
    parts = ['/* generated by tools/embed_lua.py from host/addons/lua/ - do not edit */',
             '#include <stddef.h>', '#include <stdio.h>', '#include <stdlib.h>', '#include <string.h>', '']
    def ident(n):
        return 's_' + ''.join(c if c.isalnum() else '_' for c in n)
    for n in names:
        data = open(path_of[n], 'rb').read()
        rows = [','.join('%d' % b for b in data[i:i + 64]) for i in range(0, len(data), 64)]
        parts.append('static const unsigned char %s[%d] = {\n%s\n};' % (ident(n), len(data) or 1, ',\n'.join(rows) or '0'))
    parts.append('')
    parts.append('static const struct { const char* name; const unsigned char* data; size_t size; } FILES[] = {')
    for n in names:
        parts.append('    { "%s", %s, %d },' % (n, ident(n), os.path.getsize(path_of[n])))
    parts.append('};')
    parts.append('''
/* FFXI_ADDONS_LUA=<folder>: the files there instead (developing the layers without rebuilding) */
static const char* from_folder(const char* name, size_t* size)
{
    static char* cache[64];
    static char names[64][64];
    const char* dir = getenv("FFXI_ADDONS_LUA");
    if (!dir || !*dir)
        return NULL;
    for (int i = 0; i < 64; ++i)
        if (!strcmp(names[i], name))
        {
            free(cache[i]);
            cache[i] = NULL;
            names[i][0] = 0;
        }
    char path[1024];
    snprintf(path, sizeof path, "%s/%s.lua", dir, name);
    FILE* f = fopen(path, "rb");
    if (!f)
        return NULL;
    fseek(f, 0, SEEK_END);
    long n = ftell(f);
    fseek(f, 0, SEEK_SET);
    char* b = (char*)malloc((size_t)n + 1);
    if (!b || fread(b, 1, (size_t)n, f) != (size_t)n)
    {
        fclose(f);
        free(b);
        return NULL;
    }
    fclose(f);
    for (int i = 0; i < 64; ++i)
        if (!names[i][0])
        {
            snprintf(names[i], sizeof names[i], "%s", name);
            cache[i] = b;
            break;
        }
    *size = (size_t)n;
    return b;
}

const char* xi_embedded(const char* name, size_t* size)
{
    const char* dev = from_folder(name, size);
    if (dev)
        return dev;
    for (size_t i = 0; i < sizeof FILES / sizeof *FILES; ++i)
        if (!strcmp(FILES[i].name, name))
        {
            *size = FILES[i].size;
            return (const char*)FILES[i].data;
        }
    return NULL;
}
''')
    text = '\n'.join(parts)
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    try:
        if open(OUT).read() == text:
            return
    except OSError:
        pass
    open(OUT, 'w').write(text)
    print('embedded %d files' % len(names))


if __name__ == '__main__':
    sys.exit(main())
