"""Embed the addon host's Lua (host/addons/lua/*.lua) into generated/addons_lua.c.

  python3 tools/embed_lua.py

host/addons/core.c runs them from memory (xi_embedded): xi.lua in every addon's state, then the
kind's layer (ashita.lua, windower.lua) and whatever those require from the host (a module under
host/addons/lua/ is reachable as require('xi.<name>')). Rewritten only when the text changes.
"""
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
SRC = os.path.join(ROOT, 'host', 'addons', 'lua')
OUT = os.path.join(ROOT, 'generated', 'addons_lua.c')


def main():
    names = sorted(f[:-4] for f in os.listdir(SRC) if f.endswith('.lua'))
    parts = ['/* generated by tools/embed_lua.py from host/addons/lua/ - do not edit */',
             '#include <stddef.h>', '#include <string.h>', '']
    for n in names:
        data = open(os.path.join(SRC, n + '.lua'), 'rb').read()
        rows = [', '.join('%d' % b for b in data[i:i + 32]) for i in range(0, len(data), 32)]
        parts.append('static const unsigned char s_%s[%d] = {\n    %s\n};' % (n, len(data) or 1, ',\n    '.join(rows) or '0'))
    parts.append('')
    parts.append('static const struct { const char* name; const unsigned char* data; size_t size; } FILES[] = {')
    for n in names:
        size = os.path.getsize(os.path.join(SRC, n + '.lua'))
        parts.append('    { "%s", s_%s, %d },' % (n, n, size))
    parts.append('};')
    parts.append('''
const char* xi_embedded(const char* name, size_t* size)
{
    for (size_t i = 0; i < sizeof FILES / sizeof *FILES; ++i)
        if (!strcmp(FILES[i].name, name))
        {
            *size = FILES[i].size;
            return (const char*)FILES[i].data;
        }
    return NULL;
}
''')
    text = '\n'.join(parts)
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    try:
        if open(OUT).read() == text:
            return
    except OSError:
        pass
    open(OUT, 'w').write(text)
    print('embedded %d Lua files' % len(names))


if __name__ == '__main__':
    sys.exit(main())
